// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package ds.hdfs.test;

public interface TestReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ds.hdfs.test.TestReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string test_reply_field = 1;</code>
   * @return The testReplyField.
   */
  java.lang.String getTestReplyField();
  /**
   * <code>string test_reply_field = 1;</code>
   * @return The bytes for testReplyField.
   */
  com.google.protobuf.ByteString
      getTestReplyFieldBytes();
}
