// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package ds.hdfs.test;

/**
 * <pre>
 * The greeting service definition.
 * </pre>
 *
 * Protobuf service {@code ds.hdfs.test.TestService}
 */
public  abstract class TestService
    implements com.google.protobuf.Service {
  protected TestService() {}

  public interface Interface {
    /**
     * <code>rpc TestThisService(.ds.hdfs.test.TestRequest) returns (.ds.hdfs.test.TestReply);</code>
     */
    public abstract void testThisService(
        com.google.protobuf.RpcController controller,
        ds.hdfs.test.TestRequest request,
        com.google.protobuf.RpcCallback<ds.hdfs.test.TestReply> done);

  }

  public static com.google.protobuf.Service newReflectiveService(
      final Interface impl) {
    return new TestService() {
      @java.lang.Override
      public  void testThisService(
          com.google.protobuf.RpcController controller,
          ds.hdfs.test.TestRequest request,
          com.google.protobuf.RpcCallback<ds.hdfs.test.TestReply> done) {
        impl.testThisService(controller, request, done);
      }

    };
  }

  public static com.google.protobuf.BlockingService
      newReflectiveBlockingService(final BlockingInterface impl) {
    return new com.google.protobuf.BlockingService() {
      public final com.google.protobuf.Descriptors.ServiceDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }

      public final com.google.protobuf.Message callBlockingMethod(
          com.google.protobuf.Descriptors.MethodDescriptor method,
          com.google.protobuf.RpcController controller,
          com.google.protobuf.Message request)
          throws com.google.protobuf.ServiceException {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.callBlockingMethod() given method descriptor for " +
            "wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return impl.testThisService(controller, (ds.hdfs.test.TestRequest)request);
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getRequestPrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getRequestPrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return ds.hdfs.test.TestRequest.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getResponsePrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getResponsePrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return ds.hdfs.test.TestReply.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

    };
  }

  /**
   * <code>rpc TestThisService(.ds.hdfs.test.TestRequest) returns (.ds.hdfs.test.TestReply);</code>
   */
  public abstract void testThisService(
      com.google.protobuf.RpcController controller,
      ds.hdfs.test.TestRequest request,
      com.google.protobuf.RpcCallback<ds.hdfs.test.TestReply> done);

  public static final
      com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptor() {
    return ds.hdfs.test.TestProto.getDescriptor().getServices().get(0);
  }
  public final com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }

  public final void callMethod(
      com.google.protobuf.Descriptors.MethodDescriptor method,
      com.google.protobuf.RpcController controller,
      com.google.protobuf.Message request,
      com.google.protobuf.RpcCallback<
        com.google.protobuf.Message> done) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.callMethod() given method descriptor for wrong " +
        "service type.");
    }
    switch(method.getIndex()) {
      case 0:
        this.testThisService(controller, (ds.hdfs.test.TestRequest)request,
          com.google.protobuf.RpcUtil.<ds.hdfs.test.TestReply>specializeCallback(
            done));
        return;
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getRequestPrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getRequestPrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return ds.hdfs.test.TestRequest.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getResponsePrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getResponsePrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return ds.hdfs.test.TestReply.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public static Stub newStub(
      com.google.protobuf.RpcChannel channel) {
    return new Stub(channel);
  }

  public static final class Stub extends ds.hdfs.test.TestService implements Interface {
    private Stub(com.google.protobuf.RpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.RpcChannel channel;

    public com.google.protobuf.RpcChannel getChannel() {
      return channel;
    }

    public  void testThisService(
        com.google.protobuf.RpcController controller,
        ds.hdfs.test.TestRequest request,
        com.google.protobuf.RpcCallback<ds.hdfs.test.TestReply> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        ds.hdfs.test.TestReply.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          ds.hdfs.test.TestReply.class,
          ds.hdfs.test.TestReply.getDefaultInstance()));
    }
  }

  public static BlockingInterface newBlockingStub(
      com.google.protobuf.BlockingRpcChannel channel) {
    return new BlockingStub(channel);
  }

  public interface BlockingInterface {
    public ds.hdfs.test.TestReply testThisService(
        com.google.protobuf.RpcController controller,
        ds.hdfs.test.TestRequest request)
        throws com.google.protobuf.ServiceException;
  }

  public static final class BlockingStub implements BlockingInterface {
    private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.BlockingRpcChannel channel;

    public ds.hdfs.test.TestReply testThisService(
        com.google.protobuf.RpcController controller,
        ds.hdfs.test.TestRequest request)
        throws com.google.protobuf.ServiceException {
      return (ds.hdfs.test.TestReply) channel.callBlockingMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        ds.hdfs.test.TestReply.getDefaultInstance());
    }

  }

  // @@protoc_insertion_point(class_scope:ds.hdfs.test.TestService)
}

