// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package example.test;

public interface TestRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:example.test.TestRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string test_request_field = 1;</code>
   * @return The testRequestField.
   */
  java.lang.String getTestRequestField();
  /**
   * <code>string test_request_field = 1;</code>
   * @return The bytes for testRequestField.
   */
  com.google.protobuf.ByteString
      getTestRequestFieldBytes();
}
