// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package tests.test;

public final class TestProto {
  private TestProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ds_hdfs_test_TestRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ds_hdfs_test_TestRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ds_hdfs_test_TestReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ds_hdfs_test_TestReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ntest.proto\022\014ds.hdfs.test\")\n\013TestReques" +
      "t\022\032\n\022test_request_field\030\001 \001(\t\"%\n\tTestRep" +
      "ly\022\030\n\020test_reply_field\030\001 \001(\t2V\n\013TestServ" +
      "ice\022G\n\017TestThisService\022\031.tests.test.Te" +
      "stRequest\032\027.tests.test.TestReply\"\000B\036\n\014" +
      "ds.hdfs.testB\tTestProtoP\001\210\001\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ds_hdfs_test_TestRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ds_hdfs_test_TestRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ds_hdfs_test_TestRequest_descriptor,
        new java.lang.String[] { "TestRequestField", });
    internal_static_ds_hdfs_test_TestReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ds_hdfs_test_TestReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ds_hdfs_test_TestReply_descriptor,
        new java.lang.String[] { "TestReplyField", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
